---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: api-gateway-system
spec:
  secretName: gateway-tls-nip-io
  commonName: nip.io
  subject:
    organizations:
      - "tmax-cloud"
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - "nip.io"
    - "{{TRAEFIK_IP}}.nip.io"
    - "*.{{TRAEFIK_IP}}.nip.io"
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer