apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
    "receivers":
      - "name": "default-receiver"
    "route":
      "group_wait": "10s"
      "group_interval": "5m"
      "receiver": "default-receiver"
      "repeat_interval": "3h"
type: Opaque
