kind: Service
apiVersion: v1
metadata:
  name: etcd
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  ports:
    - name: http
      protocol: TCP
      port: 2381
      targetPort: 2381
  selector:
    k8s-app: etcd
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
