kind: Service
apiVersion: v1
metadata:
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 10251
      targetPort: 10251
  selector:
    k8s-app: kube-scheduler
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}