---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmaxcloud-gateway-selfsigned
  namespace: api-gateway-system
spec:
  secretName: tmaxcloud-gateway-selfsigned
  commonName: api-gateway
  subject:
    organizations:
      - "tmax-cloud"
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - "api-gateway.api-gateway-system.svc"
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
