apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - args:
            - --entryPoints.traefik.address=:9000
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --entrypoints.websecure.http.middlewares=cors-header@file
            - --entrypoints.websecure.http.tls
            - --entryPoints.k8s.address=:6443
            - --entrypoints.k8s.http.tls
            - --entryPoints.9001.address=:9001
            - --entrypoints.9001.http.tls
            - --entryPoints.9002.address=:9002
            - --entrypoints.9002.http.tls
            - --entryPoints.9003.address=:9003
            - --entrypoints.9003.http.tls
            ## insecureSkipVerify disables SSL certificate verification.
            - --serverstransport.insecureskipverify=true # disables SSL certificate verification. (verify ssl certificate beween traefik - backend)
            ## user rootCAs :rootCAs is the list of certificates (as file paths, or data bytes) that will be set as Root Certificate Authorities when using a self-signed TLS certificate.
            # - --serverstransport.rootcas=/run/secrets/tmaxcloud/ca.crt, /run/secrets/kubernetes.io/serviceaccount/ca.crt
            # Uncomment the below lines to redirect http requests to https.
            - --entryPoints.web.http.redirections.entrypoint.to=websecure
            - --entryPoints.web.http.redirections.entrypoint.scheme=https
            - --api=true
            - --ping=true
            - --providers.kubernetesingress=true
            - --providers.kubernetesingress.ingressclass=tmax-cloud
            - --providers.kubernetesingress.ingressendpoint.publishedservice=api-gateway-system/api-gateway
            - --providers.kubernetesingress.allowemptyservices=true
            - --providers.kubernetesingress.allowexternalnameservices=true
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --providers.kubernetesgateway=true
            - --providers.file
            - --providers.file.directory=/data/config
            - --providers.file.watch=true
            - --log=true
            - --log.level=ERROR
            - --log.format=common
            - --accesslog=true
            - --accesslog.format=json
            - --accesslog.filepath=/var/log/gateway/access.log
            - --accesslog.bufferingsize=300
            - --accesslog.fields.headers.defaultmode=drop
            - --accesslog.filters.statuscodes=300-600
          image: traefik:v2.5.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: traefik
          ports:
            - containerPort: 9000
              name: traefik
              protocol: TCP
            - containerPort: 80
              name: web
              protocol: TCP
            - containerPort: 443
              name: websecure
              protocol: TCP
            - containerPort: 6443
              name: k8s
              protocol: TCP
            - containerPort: 9001
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/config
              name: configmap-volume
              readOnly: true
            - mountPath: /run/secrets/tmaxcloud
              name: ca-secret
              readOnly: true
            - name: logs
              mountPath: /var/log/gateway
      serviceAccountName: api-gateway
      terminationGracePeriodSeconds: 60
      volumes:
        - name: configmap-volume
          configMap:
            name: gateway-config
        - name: ca-secret
          secret:
            defaultMode: 288
            secretName: tmaxcloud-gateway-selfsigned
        - name: logs
          emptyDir: {}
#      imagePullSecrets:
#        - name: regcred
