apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 001_serviceaccount.yaml
- 002_certificate.yaml
- 003_config.yaml
- 002_ingressclass.yaml
- 004_deploy.yaml
- 005_service.yaml
namespace: api-gateway-system
commonLabels:
  app.kubernetes.io/managed-by: tmax-cloud
  app.kubernetes.io/component: reverse-proxy
  app.kubernetes.io/part-of: api-gateway
  app.kubernetes.io/name: traefik
images:
- name: tmaxcloudck/jwt-decode
  newName: docker.io/tmaxcloudck/jwt-decode
  newTag: 5.0.0.1
- name: traefik
  newName: docker.io/library/traefik
  newTag: v2.5.4
configMapGenerator:
- behavior: replace
  files:
  - traefik.yml
  name: gateway-config
  namespace: api-gateway-system