apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: catalog-catalog-webhook
  namespace: "catalog"
webhooks:
- name: mutating.clusterservicebrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-clusterservicebrokers"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["clusterservicebrokers"]
- name: mutating.clusterserviceclasses.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-clusterserviceclasses"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["clusterserviceclasses"]
- name: mutating.serviceclasses.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-serviceclasses"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["serviceclasses"]
- name: mutating.clusterserviceplans.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-clusterserviceplans"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["clusterserviceplans"]
- name: mutating.serviceplans.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-serviceplans"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["serviceplans"]
- name: mutating.servicebindings.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-servicebindings"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["servicebindings"]
- name: mutating.servicebrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-servicebrokers"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["servicebrokers"]
- name: mutating.serviceinstances.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/mutating-serviceinstances"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["serviceinstances"]
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: catalog-catalog-validating-webhook
  namespace: "catalog"
webhooks:
- name: validating.status.servicebindings.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-servicebindings/status"
  failurePolicy: Fail
  rules:
  - operations: [ "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["servicebindings/status"]
- name: validating.status.servicbrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-servicebrokers/status"
  failurePolicy: Fail
  rules:
  - operations: [ "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["servicebrokers/status"]
- name: validating.status.clusterservicbrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-clusterservicebrokers/status"
  failurePolicy: Fail
  rules:
  - operations: [ "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["clusterservicebrokers/status"]
- name: validating.serviceinstances.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-serviceinstances"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["serviceinstances"]
- name: validating.clusterservicebrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-clusterservicebrokers"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["clusterservicebrokers"]
- name: validating.servicebindings.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-servicebindings"
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["v1beta1"]
    resources: ["servicebindings"]
- name: validating.servicebrokers.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-servicebrokers"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["servicebrokers"]
- name: validating.serviceclasses.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-serviceclasses"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["serviceclasses"]
- name: validating.clusterserviceclasses.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-clusterserviceclasses"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["clusterserviceclasses"]
- name: validating.serviceplans.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-serviceplans"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["serviceplans"]
- name: validating.clusterserviceplans.servicecatalog.k8s.io
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: catalog-catalog-webhook
      namespace: "catalog"
      path: "/validating-clusterserviceplans"
  failurePolicy: Fail
  rules:
    - operations: [ "CREATE", "UPDATE" ]
      apiGroups: ["servicecatalog.k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["clusterserviceplans"]
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-catalog-webhook-cert
  namespace: "catalog"
  labels:
    app: catalog-catalog-webhook
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}