kind: Service
apiVersion: v1
metadata:
  name: catalog-catalog-webhook
  namespace: "catalog"
  labels:
    app: catalog-catalog-webhook
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"
spec:
  type: NodePort
  selector:
    app: catalog-catalog-webhook
  ports:
  - name: secure
    protocol: TCP
    port: 443
    targetPort: 8443  
    nodePort: 31443
   
