apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: api-gateway-system
spec:
  type: ClusterIP
  selector:
    app: console
  ports:
  - port: 31303
    targetPort: console
    name: console
