apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmaxcloud-ca
  namespace: cert-manager
spec:
  commonName: tmaxcloud
  duration: 8760h # 360d=1y
  isCA: true
  issuerRef:
    name: tmaxcloud-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  renewBefore: 720h # 30d
  secretName: tmaxcloud-ca
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
