apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-tsb-role
rules:
- apiGroups: ["tmax.io"]
  resources: ["templates", "templateinstances", "clustertemplates"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "services"]
  verbs: ["get", "list"]