apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-template-service-broker
  name: cluster-template-service-broker
  namespace: cluster-tsb-ns
spec:
  selector:
    app: cluster-template-service-broker
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer