apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-tsb-rb
subjects:
- kind: ServiceAccount
  name: cluster-tsb-sa
  namespace: cluster-tsb-ns
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-tsb-role
  apiGroup: rbac.authorization.k8s.io