apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-operator
  namespace: template
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: template-operator
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: template-operator
subjects:
- kind: ServiceAccount
  name: template-operator
  namespace: template
roleRef:
  kind: ClusterRole
  name: template-operator
  apiGroup: rbac.authorization.k8s.io
