apiVersion: v1
kind: Service
metadata:
  name: jwt-decode-auth
  namespace: api-gateway-system
spec:
  type: ClusterIP
  selector:
    app: jwt-decode-auth
  ports:
  - port: 8080
    protocol: TCP
    targetPort: jwt-decode-auth
