apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tsb-rb
  namespace: tsb-ns
subjects:
- kind: ServiceAccount
  name: tsb-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: tsb-role
  apiGroup: rbac.authorization.k8s.io