apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-service-broker
  name: template-service-broker
  namespace: tsb-ns
spec:
  selector:
    app: template-service-broker
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer