apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsb-role
  namespace: tsb-ns
rules:
- apiGroups: ["tmax.io"]
  resources: ["templates", "templateinstances"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "services"]
  verbs: ["get", "list"]