apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 000_route53-secret.yaml
  - 000_issuer_acme_route53.yaml
  - 001_certificate.yaml
  - 002_default_tls.yaml
namespace: api-gateway-system
secretGenerator:
  - behavior: replace
    files:
      - secret_access_key
    name: route53-secret
    namespace: api-gateway-system