kind: Service
apiVersion: v1
metadata:
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 10252
      targetPort: 10252
  selector:
    k8s-app: kube-controller-manager
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
